services:
  mysql:
    container_name: 'readme-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=readme'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'